import { FormEvent, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { Album, ApiError, Assignment, CatalogueAttribution, Project, Rating, api } from "./api.generated";
import "./styles.css";

type View = "today" | "catalogue" | "history";
function Attribution({ source }: { source: CatalogueAttribution }) { return <p className="attribution">Catalogue: <a href={source.source_url} target="_blank" rel="noreferrer">{source.attribution_text}</a> · {source.source_license}</p>; }
function AlbumCard({ album }: { album: Album }) { return <article className="album"><span>#{album.rank}</span><div><h3>{album.title}</h3><p>{album.artist_credit}{album.release_year ? ` · ${album.release_year}` : ""}</p></div></article>; }
function App() {
  const [view, setView] = useState<View>("today"); const [projects, setProjects] = useState<Project[]>([]); const [projectId, setProjectId] = useState(""); const [projectName, setProjectName] = useState(""); const [today, setToday] = useState<Assignment | null>(null); const [history, setHistory] = useState<Assignment[]>([]); const [albums, setAlbums] = useState<Album[]>([]); const [attribution, setAttribution] = useState<CatalogueAttribution | null>(null); const [rating, setRating] = useState<Rating | null>(null); const [review, setReview] = useState(""); const [score, setScore] = useState(5); const [loading, setLoading] = useState(false); const [notice, setNotice] = useState("Create a local project to begin your journey.");
  const explain = (error: unknown) => error instanceof ApiError && error.status === 404 ? "This part of the local API is not connected yet." : "The local API is temporarily unavailable.";
  useEffect(() => { void loadProjects(); }, []); useEffect(() => { if (projectId) void loadHistory(projectId); }, [projectId]);
  async function loadProjects() { try { const items = await api.projects(); setProjects(items); setProjectId((current) => current || items[0]?.id || ""); } catch (error) { setNotice(explain(error)); } }
  async function createProject(event: FormEvent) { event.preventDefault(); if (!projectName.trim()) return; try { const project = await api.createProject(projectName.trim(), Intl.DateTimeFormat().resolvedOptions().timeZone); setProjects((items) => [...items, project]); setProjectId(project.id); setProjectName(""); setNotice("Project created locally."); } catch (error) { setNotice(explain(error)); } }
  async function loadToday() { if (!projectId) return setNotice("Choose or create a project first."); setLoading(true); try { const assignment = await api.generateAssignment(projectId); setToday(assignment); setAttribution(assignment.catalogue_attribution); setNotice("Your assignment is ready."); void loadHistory(projectId); } catch (error) { setNotice(explain(error)); } finally { setLoading(false); } }
  async function loadHistory(id: string) { try { const items = await api.assignments(id); setHistory(items); if (items[0]) setAttribution(items[0].catalogue_attribution); } catch { /* connected when Agent 4 supplies history */ } }
  async function loadCatalogue() { setView("catalogue"); setLoading(true); try { const page = await api.albums(); setAlbums(page.items); setAttribution(page.catalogue_attribution); } catch (error) { setNotice(explain(error)); } finally { setLoading(false); } }
  async function saveRating(event: FormEvent) { event.preventDefault(); if (!today) return; try { setRating(await api.saveRating(today.id, score, review)); setNotice("Your private rating was saved locally."); } catch (error) { setNotice(explain(error)); } }
  return <main className="shell"><header><p className="eyebrow">LOCAL ALBUM JOURNEY</p><h1>500 Albums BR</h1><p className="subhead">One record at a time, entirely on your machine.</p></header><nav aria-label="Main navigation"><button className={view === "today" ? "active" : ""} onClick={() => setView("today")}>Today</button><button className={view === "catalogue" ? "active" : ""} onClick={loadCatalogue}>Catalogue</button><button className={view === "history" ? "active" : ""} onClick={() => setView("history")}>History</button></nav><section className="project-bar"><label>Project <select value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="">Choose a project</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><form onSubmit={createProject}><input value={projectName} onChange={(event) => setProjectName(event.target.value)} placeholder="New project name" aria-label="New project name" /><button>Create</button></form></section><p className="notice" role="status">{loading ? "Loading…" : notice}</p>{view === "today" && <section className="panel"><h2>Today’s album</h2>{today ? <><AlbumCard album={today.album} /><p className="date">Assigned for {today.local_date}</p><form className="rating" onSubmit={saveRating}><label>Rating <select value={score} onChange={(event) => setScore(Number(event.target.value))}>{[1,2,3,4,5].map((value) => <option key={value} value={value}>{value} / 5</option>)}</select></label><textarea value={review} onChange={(event) => setReview(event.target.value)} placeholder="Private notes (never sent to catalogue sources)" /><button>Save private rating</button>{rating && <span>Saved</span>}</form></> : <button className="primary" disabled={loading} onClick={loadToday}>Choose today’s album</button>}</section>}{view === "catalogue" && <section className="panel"><h2>Catalogue</h2>{albums.length ? <div className="album-list">{albums.map((album) => <AlbumCard key={album.id} album={album} />)}</div> : <p>The attributed catalogue will appear here after its local API route is available.</p>}</section>}{view === "history" && <section className="panel"><h2>History</h2>{history.length ? <div className="album-list">{history.map((assignment) => <div key={assignment.id}><AlbumCard album={assignment.album} /><p className="date">{assignment.local_date}</p></div>)}</div> : <p>Your completed albums will appear here once the local history route is connected.</p>}</section>}{attribution && <Attribution source={attribution} />}<footer>Private ratings and reviews stay in the local application. The browser never contacts third-party catalogue services.</footer></main>;
}
createRoot(document.getElementById("root")!).render(<App />);
